const ActionTypes = {
  SET_USER: 'SET_USER',
  ADD_ITEM: 'ADD_ITEM',
  FETCH_MEDIAITEMS_START: 'FETCH_MEDIAITEMS_START',
  FETCH_MEDIAITEMS_SUCCESS: 'FETCH_MEDIAITEMS_SUCCESS',
  FETCH_MEDIAITEMS_FAILURE: 'FETCH_MEDIAITEMS_FAILURE',
  GET_MEDIA_ITEMS: 'GET_MEDIA_ITEMS',
  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  USER_REGISTRATION_START: 'USER_REGISTRATION_START',
  USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
  USER_REGISTRATION_FAILURE: 'USER_REGISTRATION_FAILURE'
  
};

export default ActionTypes;